### ISSUE TITLE
TEMPLATE Create Upcoming and Past Archives Pages

### ISSUE THREAD

**Issue by mauteri** [GatherPress/gatherpress#116]
domain.com/events/upcoming
domain.com/events/past

For topics...
domain.com/topic/term/upcoming
domain.com/topic/term/past
(remove domain.com/topic/term as that will be based on publish date)

**Comment by evertiro** [comment]
This needs to be better thought out - having `/events/upcoming` and `/events/past` without having anything on `/events` will inevitably result in _some_ user saying bad UX. 

`/events` should do something more than a 404 error. Maybe display all upcoming? Maybe display all? Maybe redirect to upcoming? I'd favor displaying something rather than redirecting in case the user wants to override that template specifically.

`/events/upcoming` and `/events/past` are fine as is.

We should also consider adding `/events/all` (if `/events` isn't used for all).

**Comment by mauteri** [comment]
Good thoughts, maybe for this ticket we start with `/events/upcoming` and `/events/past` and then continue to discuss ideas for `/events`. If you can get upcoming and past events on `/events`, I'm curious how that code would work/look.

**Comment by mauteri** [comment]
This would also apply to how we handle events displayed with Topic terms (second point of this ticket).

**Comment by mauteri** [comment]
@evertiro Maybe we have this in settings, ie, assign a page to the archive of upcoming/past much like you can assign a page to `blog` in default WP. The the admin user can decide how this should work and makes it super flexible for them.
