### ISSUE TITLE
Fresh Install - Dec 2021

### ISSUE THREAD

**Issue by MervinHernandez** [GatherPress/gatherpress#37]
Noting observations as I go.

**Comment by MervinHernandez** [comment]
Fresh install - created an event, when populating start/end times for events, I saw the site was default to UTC-0.  
1. I populated 3am while still at UTC-0.
2. I then changed the WP time zone to "Chicago"
3. Returning to edit the event, the time remained at 3am ... irrespective of the time zone change just made.

**Comment by MervinHernandez** [comment]
✅ Confirming adding blocks is working as expected
✅ Confirming change of "Menu Structure" is working as expected
✅ Suggested rewording this #38

**Comment by MervinHernandez** [comment]
👋 Completed fresh install test. 
@mauteri you can comment on observations above, and close this ticket.

**Comment by mauteri** [comment]
> Fresh install - created an event, when populating start/end times for events, I saw the site was default to UTC-0.
> 
> 1. I populated 3am while still at UTC-0.
> 2. I then changed the WP time zone to "Chicago"
> 3. Returning to edit the event, the time remained at 3am ... irrespective of the time zone change just made.

@MervinHernandez i'll create a ticket for this with your notes. looks like a bug. thx!

**Comment by mauteri** [comment]
@MervinHernandez actually, this might be intentional. i think the plan is to have a place to select timezone (not built yet), which is pre-filled with the timezone set for the site. the timezone for each event is saved to the database. That way, with the same account, you can create an event that is set to chicago vs new york if you like. might need to think this through a little more. this is mostly for the backend... eventually, we want to be able to sense the user's timezone and adjust. so if i see an event in LA, it should test me when it is in EST, so i don't have to figure out the time difference.

**Comment by mauteri** [comment]
@MervinHernandez also, reason we don't want the date/time to change on a created event after change site timezone: let's say we have a group that was based in a city in central time (but is right on the border of eastern). if that group changes hands to someone that is a few miles away but in eastern time, if they change the timezone it would mess up the date/times of past events, which isn't what we want.

**Comment by MervinHernandez** [comment]
Acknowledged
