### ISSUE TITLE
compatibility with github updater

### ISSUE THREAD

**Issue by shawfactor** [GatherPress/gatherpress#600]
### Is your enhancement related to a problem? Please describe.

I imagine the plan is to put this in the repository eventually but as an interim would it be possible to make the plugin compliant with git updater?

This has become a defactor standard for automating plugin updates from github repositories, and would make testig the latest version for myself and others much easier.

https://git-updater.com/

Pete

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by carstingaxion** [comment]
Hello @shawfactor ,

I guess this will not be possible, because it would require to the break with the wp.org/plugin-guidelines, because of the additional plugin-header needed. 

Alternatively, I think it might not be a problem to link this repo to https://packagist.org/, as GatherPress already includes a `composer.json`. At latest, when the plugin is available on wp.org, you can also use https://wpackagist.org

Any opinions on a submission to packagist.org @mauteri ?

Btw. Composer is _my_ personal defacto standard.

**Comment by shawfactor** [comment]
@carstingaxion 

I use the repository for updates with a fallback to GitHub updater. 

My interest in this was as an interim until the plugin was added to the Wordpress repository as I wanted to iterate my own plugin development from the latest version of gatherpress (I’ve a few custom plugins that work with events and I now use gather press for events)

What is the likely timeline for gatherpress being in the repository? If that is soon then that will be fine for me and I’d expect most others

**Comment by carstingaxion** [comment]
> What is the likely timeline for gatherpress being in the repository? 

Don’t know for sure, but given that @mauteri wanted to send the 0.29.0 version back to the review team, which will be released in the next days AND that the review team currently has a _- how do they call it -_ reply-delay of around 3 weeks (which I know from a recent submission), it might happen within the next month.

**Comment by mauteri** [comment]
0.29.0 is being submitted to the plugin repository this week and should take about 10 days as it has already been reviewed once already.
