### ISSUE TITLE
Login Required modal has [object Object] as text

### ISSUE THREAD

**Issue by mauteri** [GatherPress/gatherpress#623]
### Describe the bug

This appears to be a recent bug as I just noticed it. Some JavaScript needs to be revisited as it was once seen as a string but now as an object.

### Steps to Reproduce

1. Make sure you are not logged 
2. Click RSVP button to RSVP to an event.
3. Login modal pops up with the reported issue. (see screenshot)

### Screenshots, screen recording, code snippet

![image](https://github.com/GatherPress/gatherpress/assets/818980/56196965-c6c6-424b-b5a2-8a5740cfd10a)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jmarx** [comment]
@carstingaxion Can you take look at these kind of commits please?
https://github.com/GatherPress/gatherpress/commit/a86f41e5f7cd294ac0c8e682eb96c2e86dbf6469
https://github.com/GatherPress/gatherpress/commit/142cd01c3cfcb5f4c2d2f8ddad7ea3dad2a25224

This issue is being caused by wrapping the registration links into sprintfs/HtmlReactParser syntax.
When reverting those commits, it works as expected.
