### ISSUE TITLE
Make some protected methods public

### ISSUE THREAD

**Issue by shawfactor** [GatherPress/gatherpress#635]
### Is your enhancement related to a problem? Please describe.

ATM the get_formatted_datetime and get_calendar_description methods within the event class are protected. Is there a good reason for this. I ask as I was building my own plugin based on yours and needed them but they are protected. AFAICT there are no aternatives to this for getting local datetimes or descriptions that devs can utlise and I cannot see a security implication. 

Can this be fixed?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shawfactor** [comment]
following up on this, although I think this needs to be broader. I think there needs to be a review of all methods in this plugin. There are many protected methords that should be public e.g. get_formatted_datetime and many public methods that should be public static e.g. get_venue_post_from_term_slug

The underlying point being people will want to build functionality on top of this plugin (I am doing this atm) and if it is safe useful methods should be accessible to people who want to build functionaity

**Comment by mauteri** [comment]
@shawfactor This seems reasonable. I'm unsure why some of those methods are protected. Thanks for flagging this and feel free if you like to put in a pull request to change some methods you need made public. We're always looking for new contributors. :-) If you'd rather not put in a PR, that's fine too. I can flag this for `0.31.0` since `0.30.0` is pretty much done and being tested at the moment.
