### ISSUE TITLE
NEW Event Date block 

### ISSUE THREAD

**Issue by carstingaxion** [GatherPress/gatherpress#684]
### Is your enhancement related to a problem? Please describe.

A new or updated Event Date block should …:

- [ ] show the start date only
- [ ] Show the end date only
- [ ] Show start and end date
- [ ] use the time and date formats saved in settings, by default 
- [ ] Allow to set a custom format
- [ ] Should have proper documentation, incl. https://github.com/GatherPress/gatherpress/issues/727#issuecomment-2226563698

With that in place one could easily create many different layouts using one or multiple instances of the Event Date block within a singular or archive template, or even within a query block.

The UI for both dates should be merged into one, because people will probably ever want to define an end date, after they defined a start date. This should the save two-clicks for closing start- and opening end-date-fields.

### Designs

The existing `core/post-date` has the most of what is needed, but is not prepared well to create block-variations from. Maybe GatherPress can re-use some of its components.

Fixing the variation-problem in the [source at Gutenberg](https://github.com/WordPress/gutenberg/issues?q=is%3Aissue+is%3Aopen+post-date+label%3A%22%5BBlock%5D+Post+Date%22), would be best.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mauteri** [comment]
NOTES: https://github.com/WordPress/gutenberg/issues/60971

**Comment by MervinHernandez** [comment]
✅ Viewed 684 - Event Date Block - Mike has it

**Comment by MervinHernandez** [comment]
✅ Reviewed June 22 - Mike has it

**Comment by mauteri** [comment]
This will need to be a custom block as a block variation does not appear to be possible. I can still explore a bit, but I think the translations aspects of this make it pretty much impossible. We can still explore ways of replicating things done in the Post Date block to improve our current block. 

https://github.com/WordPress/gutenberg/tree/trunk/packages/block-library/src/post-date

**Comment by JordanPak** [comment]
I think I can take a look at this @mauteri @ashortpmc

**Comment by JordanPak** [comment]
Discussed in today's weekly huddle:

We want the event date block to be flexible and highly customizable, like shown in [the example](https://github.com/GatherPress/gatherpress/issues/684#issuecomment-3144429390). Adding block-based attributes for the date/time formatting that override the plugin's settings makes sense, but we also have overrides at the **user** level (in their profile). This would basically break arrangements like the example where multiple event date blocks are used with different formatting, since every block would just get overridden multiple times, resulting in a ton of redundant and buggy displays.

@mauteri said that the user settings were introduced so those who prefer 24 hour time or DD/MM/YYYY can see dates like that on the site. We decided to meet in the middle:

1. Replace the "Time Format" option with one that allows the user to select 12 or 24 hour time. It should then be a relatively straightforward `h` to `H` and `g` to `G` swap in the `Event`'s formatting methods.
1. Remove the "Date Format" option for now--it's much harder to make it work with these new block-based options than time, and basically only relevant if the site is using `m/j/Y` or similar, which likely isn't that common. We could potentially add a "known date patterns" functionality to the roadmap to catch cases like `m/jY` and have a user preference that would cause them to convert  to `j/m/Y` before render.

**Comment by carstingaxion** [comment]
> Discussed in today's weekly huddle:
> 
> We want the event date block to be flexible and highly customizable, like shown in [the example](https://github.com/GatherPress/gatherpress/issues/684#issuecomment-3144429390). Adding block-based attributes for the date/time formatting that override the plugin's settings makes sense

Great you took the time, thanks.

> but we also have overrides at the **user** level (in their profile). This would basically break arrangements like the example where multiple event date blocks are used with different formatting, since every block would just get overridden multiple times, resulting in a ton of redundant and buggy displays

I still believe this could be done. IMHO all automated changes that can appear to the date, like removing a redundant date for same day events or the overrides from user settings, **should only happen to the default, unchanged instance of the block**. As soon as some editor have chosen for a custom display format, no further changes should be applied to the rendering.

The user-setting override feature in general is only relevant for community websites with an active user base, which might not be everyone’s use case.
