### ISSUE TITLE
ADD Event URL (Event Venue)

### ISSUE THREAD

**Issue by mauteri** [GatherPress/gatherpress#82]
# Feature Description
**Updated: Zoom Module v1 Scope**
Start with simple link that can be Zoom or anything else (like Meetup does).

**Queued: Zoom Module v2 Scope**
Eventually explore integrating Zoom link as an embeddable block for events to make attending online super easy right from the browser.

# Test
* Only displayed if attendee is a confirmed attendee (not in the waiting list)

**Comment by MervinHernandez** [comment]
@mauteri Why don't we merge this into the "venue" feature?

## Mervin's Concept
```
if venue_type = virtual
   show post meta text box for "URL Field" 
   show post meta checkbox for "display_url_to_non_confirmed_attendees"
else
   show "address" field boxes // (as is live as of @0.5
en_if
```

**Comment by mauteri** [comment]
Good idea... We can actually just include it as part of the block along with the other information. You could theoretically have a space and want to include a Zoom link you use all the time for that space. We can also create a one-off virtual link block as well. I think having both those will add lots of flexibility. What do you think?

**Comment by MervinHernandez** [comment]
My main thought is, the "venue" post, should feed the "venue" meta for each event, in a very easy-to-consume way. So, this is my thought behind conditionally capturing the venue information (URL or a physical address) so that we can later render that appropriately in the event itself. 

Option 1: If it's an address, then the venue exact address will feed the event location with the address.

Option 2: If it's a virtual location, then the URL is displayed next to the event, if it is set to be "publicly visible". Otherwise, we show "URL displayed upon RSVP". 

Those are my thoughts.

**Comment by mauteri** [comment]
Video of meetup's workflow with virtual event (for inspiration purposes) https://www.meetup.com/blog/how-to-host-an-online-event-on-meetup/
